# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: epubcheck 3.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "epubcheck"
  s.version = "3.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["jugyo"]
  s.date = "2014-04-05"
  s.description = "This is a command-line ePub check tool. It is wrapper of epubcheck(http://code.google.com/p/epubcheck/)."
  s.email = "jugyo.org@gmail.com"
  s.executables = ["epubcheck"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "lib/epubcheck-1.0.5/COPYING.txt",
    "lib/epubcheck-1.0.5/README.txt",
    "lib/epubcheck-1.0.5/epubcheck-1.0.5.jar",
    "lib/epubcheck-1.0.5/jing_license.txt",
    "lib/epubcheck-1.0.5/lib/saxon.jar",
    "lib/epubcheck-3.0.1/COPYING.txt",
    "lib/epubcheck-3.0.1/README.txt",
    "lib/epubcheck-3.0.1/THIRD-PARTY.txt",
    "lib/epubcheck-3.0.1/epubcheck-3.0.1.jar",
    "lib/epubcheck-3.0.1/lib/Saxon-HE-9.4.0.6.jar",
    "lib/epubcheck-3.0.1/lib/commons-compress-1.4.1.jar",
    "lib/epubcheck-3.0.1/lib/guava-13.0.1.jar",
    "lib/epubcheck-3.0.1/lib/jing-20120724.0.0.jar",
    "lib/epubcheck-3.0.1/lib/sac-1.3.jar",
    "lib/epubcheck-3.0.1/licenses/Apache-2.0.txt",
    "lib/epubcheck-3.0.1/licenses/BSD-3-Clause.txt",
    "lib/epubcheck-3.0.1/licenses/MPL-1.0.txt",
    "lib/epubcheck-3.0.1/licenses/W3C.txt"
  ]
  s.homepage = "http://github.com/jugyo/epubcheck"
  s.rubygems_version = "2.2.2"
  s.summary = "command-line ePub check tool"
end

