# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "epubcheck"
  s.version = "3.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["jugyo"]
  s.date = "2013-01-22"
  s.description = "This is a command-line ePub check tool. It is wrapper of epubcheck(http://code.google.com/p/epubcheck/)."
  s.email = "jugyo.org@gmail.com"
  s.executables = ["epubcheck"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "lib/epubcheck-1.0.5/COPYING.txt",
    "lib/epubcheck-1.0.5/README.txt",
    "lib/epubcheck-1.0.5/epubcheck-1.0.5.jar",
    "lib/epubcheck-1.0.5/jing_license.txt",
    "lib/epubcheck-1.0.5/lib/saxon.jar",
    "lib/epubcheck-3.0/COPYING.txt",
    "lib/epubcheck-3.0/README.txt",
    "lib/epubcheck-3.0/THIRD-PARTY.txt",
    "lib/epubcheck-3.0/epubcheck-3.0.jar",
    "lib/epubcheck-3.0/lib/commons-compress-1.4.1.jar",
    "lib/epubcheck-3.0/lib/guava-13.0.1.jar",
    "lib/epubcheck-3.0/lib/jing-20120724.0.0.jar",
    "lib/epubcheck-3.0/lib/sac-1.3.jar",
    "lib/epubcheck-3.0/lib/saxon-9.1.0.8.jar",
    "lib/epubcheck-3.0/licenses/Apache-2.0.txt",
    "lib/epubcheck-3.0/licenses/BSD-3-Clause.txt",
    "lib/epubcheck-3.0/licenses/MPL-1.0.txt",
    "lib/epubcheck-3.0/licenses/W3C.txt"
  ]
  s.homepage = "http://github.com/jugyo/epubcheck"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "command-line ePub check tool"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

