# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: epubcheck 3.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "epubcheck"
  s.version = "3.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["jugyo"]
  s.date = "2015-09-06"
  s.description = "This is a command-line ePub check tool. It is wrapper of epubcheck(http://code.google.com/p/epubcheck/)."
  s.email = "jugyo.org@gmail.com"
  s.executables = ["epubcheck"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "lib/epubcheck-4.0.0/COPYING.txt",
    "lib/epubcheck-4.0.0/README.txt",
    "lib/epubcheck-4.0.0/THIRD-PARTY.txt",
    "lib/epubcheck-4.0.0/epubcheck.jar",
    "lib/epubcheck-4.0.0/lib/Saxon-HE-9.5.1-5.jar",
    "lib/epubcheck-4.0.0/lib/common-image-3.1.2.jar",
    "lib/epubcheck-4.0.0/lib/common-io-3.1.2.jar",
    "lib/epubcheck-4.0.0/lib/common-lang-3.1.2.jar",
    "lib/epubcheck-4.0.0/lib/commons-compress-1.5.jar",
    "lib/epubcheck-4.0.0/lib/guava-14.0.1.jar",
    "lib/epubcheck-4.0.0/lib/imageio-core-3.1.2.jar",
    "lib/epubcheck-4.0.0/lib/imageio-jpeg-3.1.2.jar",
    "lib/epubcheck-4.0.0/lib/imageio-metadata-3.1.2.jar",
    "lib/epubcheck-4.0.0/lib/jackson-core-asl-1.9.12.jar",
    "lib/epubcheck-4.0.0/lib/jackson-mapper-asl-1.9.12.jar",
    "lib/epubcheck-4.0.0/lib/jing-20120724.0.0.jar",
    "lib/epubcheck-4.0.0/lib/sac-1.3.jar",
    "lib/epubcheck-4.0.0/licenses/Apache-2.0.txt",
    "lib/epubcheck-4.0.0/licenses/BSD-3-Clause.txt",
    "lib/epubcheck-4.0.0/licenses/MPL-1.0.txt",
    "lib/epubcheck-4.0.0/licenses/W3C.txt"
  ]
  s.homepage = "http://github.com/jugyo/epubcheck"
  s.rubygems_version = "2.4.8"
  s.summary = "command-line ePub check tool"
end

